# Generated by Django 3.2.25 on 2024-09-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=254)),
                ('last_name', models.CharField(max_length=254)),
                ('address', models.CharField(max_length=254)),
                ('phone', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('email', models.EmailField(blank=True, max_length=1024, null=True)),
            ],
        ),
    ]
